---
- name: This playbook will create a file for tracking all changes
  hosts: all
  become: true
  tasks:
    - name: ceating file
      file:
        path: /home/ubuntu/demo.txt
        state: touch
---
- name: This playbook will create a directory and a file for tracking all changes
  hosts: all
  become: true
  tasks:
    - name: Creating directory
      file:
        path: /home/ubuntu/demo
        state: directory

    - name: Creating a file
      file:
        path: /home/ubuntu/demo/example.txt
        state: touch